### ISSUE TITLE
Missing messenger packet

### ISSUE THREAD

**Issue by DamienJolly** [billsonnn/nitro-react#146]
Outgoing packet `1523` is in the renderer but never used. It's used to retrieve friends list after initialization.

On habbo the client requests initialization, then upon initialization it requests the friends list and request list. Nitro expects you to send the friends list along with the initialization and never requests the friends list separately. This is not the correct order of events.

Thanks,
-Damien

**Comment by UnfamiliarLegacy** [comment]
I am not sure this issue is correct. According to my site https://sulek.dev/release/PRODUCTION-201611291003-338511768

`1523` = `GetMOTDMessageComposer` (in Nitro named `MESSENGER_FRIENDS`)
`2781` = `MessengerInitMessageComposer` (in Nitro named `MESSENGER_INIT`)

Which is correctly sent

https://github.com/billsonnn/nitro-react/blob/81702e1a58e0619fbb28332130ff79c9ba73304f/src/hooks/friends/useFriends.ts#L253
